// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZHego4_oViEymfU4gW95m8I9Oeo1BhBc',
    appId: '1:585909437765:web:3e471b6f77e1339cd16a2c',
    messagingSenderId: '585909437765',
    projectId: 'quantum-talent-410009',
    authDomain: 'quantum-talent-410009.firebaseapp.com',
    storageBucket: 'quantum-talent-410009.firebasestorage.app',
    measurementId: 'G-LX811TB58H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQB64IP5GOV0QEIagsTnu-AuLN-QPu8xw',
    appId: '1:585909437765:android:b5c545e9348519efd16a2c',
    messagingSenderId: '585909437765',
    projectId: 'quantum-talent-410009',
    storageBucket: 'quantum-talent-410009.firebasestorage.app',
  );
}
